from . import admin_commands_pb2
from . import card_attributes_pb2
from . import color_pb2
from . import command_attach_card_pb2
from . import command_change_zone_properties_pb2
from . import command_concede_pb2
from . import command_create_arrow_pb2
from . import command_create_counter_pb2
from . import command_create_token_pb2
from . import command_deck_del_dir_pb2
from . import command_deck_del_pb2
from . import command_deck_download_pb2
from . import command_deck_list_pb2
from . import command_deck_new_dir_pb2
from . import command_deck_select_pb2
from . import command_deck_upload_pb2
from . import command_del_counter_pb2
from . import command_delete_arrow_pb2
from . import command_draw_cards_pb2
from . import command_dump_zone_pb2
from . import command_flip_card_pb2
from . import command_game_say_pb2
from . import command_inc_card_counter_pb2
from . import command_inc_counter_pb2
from . import command_kick_from_game_pb2
from . import command_leave_game_pb2
from . import command_move_card_pb2
from . import command_mulligan_pb2
from . import command_next_turn_pb2
from . import command_ready_start_pb2
from . import command_replay_delete_match_pb2
from . import command_replay_download_pb2
from . import command_replay_list_pb2
from . import command_replay_modify_match_pb2
from . import command_reveal_cards_pb2
from . import command_roll_die_pb2
from . import command_set_active_phase_pb2
from . import command_set_card_attr_pb2
from . import command_set_card_counter_pb2
from . import command_set_counter_pb2
from . import command_set_sideboard_lock_pb2
from . import command_set_sideboard_plan_pb2
from . import command_shuffle_pb2
from . import command_stop_dump_zone_pb2
from . import command_undo_draw_pb2
from . import commands_pb2
from . import context_concede_pb2
from . import context_connection_state_changed_pb2
from . import context_deck_select_pb2
from . import context_move_card_pb2
from . import context_mulligan_pb2
from . import context_ping_changed_pb2
from . import context_ready_start_pb2
from . import context_set_sideboard_lock_pb2
from . import context_undo_draw_pb2
from . import event_add_to_list_pb2
from . import event_attach_card_pb2
from . import event_change_zone_properties_pb2
from . import event_connection_closed_pb2
from . import event_create_arrow_pb2
from . import event_create_counter_pb2
from . import event_create_token_pb2
from . import event_del_counter_pb2
from . import event_delete_arrow_pb2
from . import event_destroy_card_pb2
from . import event_draw_cards_pb2
from . import event_dump_zone_pb2
from . import event_flip_card_pb2
from . import event_game_closed_pb2
from . import event_game_host_changed_pb2
from . import event_game_joined_pb2
from . import event_game_say_pb2
from . import event_game_state_changed_pb2
from . import event_join_pb2
from . import event_join_room_pb2
from . import event_kicked_pb2
from . import event_leave_pb2
from . import event_leave_room_pb2
from . import event_list_games_pb2
from . import event_list_rooms_pb2
from . import event_move_card_pb2
from . import event_notify_user_pb2
from . import event_player_properties_changed_pb2
from . import event_remove_from_list_pb2
from . import event_replay_added_pb2
from . import event_reveal_cards_pb2
from . import event_roll_die_pb2
from . import event_room_say_pb2
from . import event_server_complete_list_pb2
from . import event_server_identification_pb2
from . import event_server_message_pb2
from . import event_server_shutdown_pb2
from . import event_set_active_phase_pb2
from . import event_set_active_player_pb2
from . import event_set_card_attr_pb2
from . import event_set_card_counter_pb2
from . import event_set_counter_pb2
from . import event_shuffle_pb2
from . import event_stop_dump_zone_pb2
from . import event_user_joined_pb2
from . import event_user_left_pb2
from . import event_user_message_pb2
from . import game_commands_pb2
from . import game_event_container_pb2
from . import game_event_context_pb2
from . import game_event_pb2
from . import game_replay_pb2
from . import isl_message_pb2
from . import moderator_commands_pb2
from . import move_card_to_zone_pb2
from . import response_activate_pb2
from . import response_adjust_mod_pb2
from . import response_ban_history_pb2
from . import response_deck_download_pb2
from . import response_deck_list_pb2
from . import response_deck_upload_pb2
from . import response_dump_zone_pb2
from . import response_forgotpasswordrequest_pb2
from . import response_get_games_of_user_pb2
from . import response_get_user_info_pb2
from . import response_join_room_pb2
from . import response_list_users_pb2
from . import response_login_pb2
from . import response_pb2
from . import response_register_pb2
from . import response_replay_download_pb2
from . import response_replay_list_pb2
from . import response_viewlog_history_pb2
from . import response_warn_history_pb2
from . import response_warn_list_pb2
from . import room_commands_pb2
from . import room_event_pb2
from . import server_message_pb2
from . import serverinfo_arrow_pb2
from . import serverinfo_ban_pb2
from . import serverinfo_card_pb2
from . import serverinfo_cardcounter_pb2
from . import serverinfo_chat_message_pb2
from . import serverinfo_counter_pb2
from . import serverinfo_deckstorage_pb2
from . import serverinfo_game_pb2
from . import serverinfo_gametype_pb2
from . import serverinfo_player_pb2
from . import serverinfo_playerping_pb2
from . import serverinfo_playerproperties_pb2
from . import serverinfo_replay_match_pb2
from . import serverinfo_replay_pb2
from . import serverinfo_room_pb2
from . import serverinfo_user_pb2
from . import serverinfo_warning_pb2
from . import serverinfo_zone_pb2
from . import session_commands_pb2
from . import session_event_pb2

from .extension_mapping import construct_extension_mapping

COMMAND_EXTENSION_MAP = construct_extension_mapping((
    session_commands_pb2.SessionCommand,
    room_commands_pb2.RoomCommand,
    game_commands_pb2.GameCommand,
    moderator_commands_pb2.ModeratorCommand,
    admin_commands_pb2.AdminCommand
))
