# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_mulligan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_mulligan.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x63ommand_mulligan.proto\x1a\x13game_commands.proto\"A\n\x10\x43ommand_Mulligan2-\n\x03\x65xt\x12\x0c.GameCommand\x18\xec\x07 \x01(\x0b\x32\x11.Command_Mulligan')
  ,
  dependencies=[game__commands__pb2.DESCRIPTOR,])




_COMMAND_MULLIGAN = _descriptor.Descriptor(
  name='Command_Mulligan',
  full_name='Command_Mulligan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_Mulligan.ext', index=0,
      number=1004, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['Command_Mulligan'] = _COMMAND_MULLIGAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_Mulligan = _reflection.GeneratedProtocolMessageType('Command_Mulligan', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND_MULLIGAN,
  __module__ = 'command_mulligan_pb2'
  # @@protoc_insertion_point(class_scope:Command_Mulligan)
  ))
_sym_db.RegisterMessage(Command_Mulligan)

_COMMAND_MULLIGAN.extensions_by_name['ext'].message_type = _COMMAND_MULLIGAN
game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_MULLIGAN.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
