# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_game_say.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event_game_say.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x65vent_game_say.proto\x1a\x10game_event.proto\"J\n\rEvent_GameSay\x12\x0f\n\x07message\x18\x01 \x01(\t2(\n\x03\x65xt\x12\n.GameEvent\x18\xf1\x07 \x01(\x0b\x32\x0e.Event_GameSay')
  ,
  dependencies=[game__event__pb2.DESCRIPTOR,])




_EVENT_GAMESAY = _descriptor.Descriptor(
  name='Event_GameSay',
  full_name='Event_GameSay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='Event_GameSay.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Event_GameSay.ext', index=0,
      number=1009, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['Event_GameSay'] = _EVENT_GAMESAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event_GameSay = _reflection.GeneratedProtocolMessageType('Event_GameSay', (_message.Message,), dict(
  DESCRIPTOR = _EVENT_GAMESAY,
  __module__ = 'event_game_say_pb2'
  # @@protoc_insertion_point(class_scope:Event_GameSay)
  ))
_sym_db.RegisterMessage(Event_GameSay)

_EVENT_GAMESAY.extensions_by_name['ext'].message_type = _EVENT_GAMESAY
game__event__pb2.GameEvent.RegisterExtension(_EVENT_GAMESAY.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
