# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_user_left.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import session_event_pb2 as session__event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event_user_left.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x65vent_user_left.proto\x1a\x13session_event.proto\"L\n\x0e\x45vent_UserLeft\x12\x0c\n\x04name\x18\x01 \x01(\t2,\n\x03\x65xt\x12\r.SessionEvent\x18\xf0\x07 \x01(\x0b\x32\x0f.Event_UserLeft')
  ,
  dependencies=[session__event__pb2.DESCRIPTOR,])




_EVENT_USERLEFT = _descriptor.Descriptor(
  name='Event_UserLeft',
  full_name='Event_UserLeft',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Event_UserLeft.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Event_UserLeft.ext', index=0,
      number=1008, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['Event_UserLeft'] = _EVENT_USERLEFT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event_UserLeft = _reflection.GeneratedProtocolMessageType('Event_UserLeft', (_message.Message,), dict(
  DESCRIPTOR = _EVENT_USERLEFT,
  __module__ = 'event_user_left_pb2'
  # @@protoc_insertion_point(class_scope:Event_UserLeft)
  ))
_sym_db.RegisterMessage(Event_UserLeft)

_EVENT_USERLEFT.extensions_by_name['ext'].message_type = _EVENT_USERLEFT
session__event__pb2.SessionEvent.RegisterExtension(_EVENT_USERLEFT.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
