#!/bin/sh
protoc -I=pb --python_out=pypb pb/*.proto
sed -i "" 's/^\(import.*_pb2\)/from . \1/' pypb/*.py

for filename in pypb/*.py; do
    basename=${filename/pypb\//}
    modulename=${basename/.py/}
    imports=`cat $filename | grep -E "GeneratedProtocolMessageType|EnumTypeWrapper" | cut -f 1 -d " " | sed "s/\(.*\)/    \1,/"`
    if [ -n "$imports" ]; then
        echo "from .$modulename import ("
        echo "$imports"
        echo ")";
    fi
done > pypb/__init__.py
